### ISSUE TITLE
CopyCode.user.js - Problem in inline Editor

### ISSUE THREAD

**Issue by muescha** [KeyWeeUsr/Userscripts#1]
CopyCode.user.js

when i disable the CopyCode script then i don't get this wrong behavior: 

OSX: El Capitan 10.11.6 (15G1217)
Chrome: 56.0.2924.87

> ## why:
> 
> i like to edit the file outside in an other text editor
> 
> ## when:
> 
> i use the inline editor https://github.com/Homebrew/brew/edit/master/manpages/brew-cask.1
> - hit CMD+A (select all) and CMD+C (copy)
> -open an other editor
> -hit CMD+V (insert)
> 
> ## what i see
> 
>  - not the full file is copied
>  only the visible lines are copied (+/- some more lines)
> 
> ## what i expected
> 
> - the full file is copied
> - i can insert a full file later back to the inline editor

**Comment by KeyWeeUsr** [comment]
Thanks! Fixed in 9c76bb6 🍡
