### ISSUE TITLE
CopyCode no longer working

### ISSUE THREAD

**Issue by CollinChaffin** [KeyWeeUsr/Userscripts#8]
I have not had the time to really dig in to debug, but it appears that even after disabling all other GM scripts in TM on Chrome/Windows that I do still get your branding icon, but the actual copy button/function is no longer visible.

**Comment by CollinChaffin** [comment]
EDIT:  I take that back - it only seems to appear on SOME code boxes but the large top main box if I open for instance a .js file used to also show a "copy" whereas now does not so I'm not sure if that was by design on a recent update or not.

**Comment by KeyWeeUsr** [comment]
I'm not really sure what do you mean. The button seems to work alright for me. Could you give me an example or the exact steps how to reproduce the issue?
