### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by PetrZav** [KeyWeeUsr/Userscripts#9]
Hi

the script is installed but when I find premium cache I see no choice to log it. Only update to premium.
Could you please help me what is wrong?

Thank you

Petr

![premium](https://user-images.githubusercontent.com/47270346/52162857-0cbdc480-26da-11e9-8369-9c219e58af82.png)

**Comment by KeyWeeUsr** [comment]
It was an issue on GC side. I fixed the check for premium type and it works fine for me.

Edit: Update to 1.1 script version and you should see the azure-ish link for logging the cache.

**Comment by PetrZav** [comment]
Thank you. It works again.
Petr
